import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { initGA, logPageView } from "../utils/analytics";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "IncludiTrip",
  authors: {
    name: "IncludiTrip, Ruben Arevalo, Mauro Castillo, Maviya Yaseen, Henry Tran",
  },
  description: "Generated by create next app",
  keywords: [
    "Disability",
    "Travel",
    "Travel accessibility",
    "AI Travel Disability",
    "AI",
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const router = useRouter();

  useEffect(() => {
    initGA();
    logPageView();
    router.events.on("routeChangeComplete", logPageView);
    return () => {
      router.events.off("routeChangeComplete", logPageView);
    };
  }, [router.events]);

  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
